### ISSUE TITLE
[FEATURE] Enable support for Shared Photo Library

### ISSUE THREAD

**Issue by mandarons** [mandarons/icloudpy#13]
**Use case**
As a iCloud photos user, I want to download photos from shared library so that I can have the local backup.

**Describe the solution you'd like**
The library should  download photos from shared library as if it is a regular library.

**Describe alternatives you've considered**
None available.

**Additional context**
Apple introduced shared photo libraries.

**Comment by Mrc527** [comment]
Any news on this topic?

I just switched to a shared library and I’ve lost backup of 50% of my pictures. 🙄

**Comment by tymmej** [comment]
I added support for shared library based on https://github.com/icloud-photos-downloader/icloud_photos_downloader/pull/678/files#diff-f900c3b92380701d84f248a30bdf37f011fceb31c3f7510de40596c0ac69aa17

There's no support for albums, but it looks like API problem - same info is on iCloud.co - "shared library in albums not yet supported".
