### ISSUE TITLE
[BUG] icloudpy fails to login as a user

### ISSUE THREAD

**Issue by mchonofsky** [mandarons/icloudpy#2]
**Describe the bug**
ICloudPyService fails to get login session

**To Reproduce**
1. run `api = ICloudPyService(username, password)`
2. command raises error ("missing apple_id field")

**Expected behavior**
Command completes successfully

It looks like Apple has changed, perhaps for only some connections, the headers it returns iin response to a login attempt. Thus it fails to get `dsWebAuthToken` and then _authenticate_with_token fails.

**Comment by mandarons** [comment]
@mchonofsky I am not able to find 'missing apple_id field' string anywhere in the code. Is that the exact error you see?

**Comment by 14278358** [comment]
Encountered the same problem, and this happened again for accounts without 2FA authentication.
