### ISSUE TITLE
[FEATURE] Login using App Specific Passwords

### ISSUE THREAD

**Issue by bogdancondurache** [mandarons/icloudpy#29]
**Use case**
This feature makes a lot of sense for people wanting code to run on a server, but also have some security and not disable 2FA. Apple offers app specific passwords and it's really hard finding a library to support them.

**Comment by mandarons** [comment]
This is not possible. icloudpy fakes being a web client to access iCloud.com features. iCloud.com is the only way to access Apple files and photos outside Apple's walled garden.

As I understand, for using app-specific passwords, icloudpy should be a registered app and should use Apple's *kit APIs. Registered apps only work in Apple's walled garden (no Windows or Linux). Registering an app also requires Apple developer account which costs $99/year.
