### ISSUE TITLE
[FEATURE] Directory size

### ISSUE THREAD

**Issue by gniting** [mandarons/icloudpy#44]
**Use case**
Get the size of a particular directory on iCloud drive or get the full storage size of iCloud drive. 

**Describe the solution you'd like**
Useful when running functions where every file/folder is being evaluated for a sync so that overall progress can be reported.

**Describe alternatives you've considered**
None

**Additional context**

**Comment by mandarons** [comment]
Size of particular directory is not available through iCloud API (folder size on icloud.com shows 0). But storage information is available. You can use 
```
api = ICloudPyService('jappleseed@apple.com')
print(api.account.storage)
```
